### ISSUE TITLE
Error output in build panel

### ISSUE THREAD

**Issue by OdinTech3** [timbrel/GitSavvy#1027]
I opened sublime text then the build panel opened and showed me this:
```
Please report this error to GitSavvy:

argument of type 'NoneType' is not iterable

Traceback (most recent call last):
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 215, in git
    stdout, stderr = self.decode_stdout(stdout), self.decode_stdout(stderr)
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 265, in decode_stdout
    fallback_encoding = self.savvy_settings.get("fallback_encoding")
  File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/settings.py", line 14, in get
    if key in project_savvy_settings:
TypeError: argument of type 'NoneType' is not iterable
```

    Sublime Text version number: Build 3179
    Git version number: 2.17.1
    OS type and version: OSX High Sierra

**Comment by randy3k** [comment]
I believe it was fixed in the dev branch (on mobile, can’t find the exact issue and pr).

**Comment by stoivo** [comment]
Yes, in https://github.com/divmain/GitSavvy/pull/1013

**Comment by kaste** [comment]
Closing as it is marked as fixed
