### ISSUE TITLE
argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Boomerml** [timbrel/GitSavvy#1044]
Please report this error to GitSavvy:

argument of type 'NoneType' is not iterable

Traceback (most recent call last):
  File "C:\Users\Кирилл\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_command.py", line 215, in git
    stdout, stderr = self.decode_stdout(stdout), self.decode_stdout(stderr)
  File "C:\Users\Кирилл\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_command.py", line 266, in decode_stdout
    silent_fallback = self.savvy_settings.get("silent_fallback")
  File "C:\Users\Кирилл\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/settings.py", line 14, in get
    if key in project_savvy_settings:
TypeError: argument of type 'NoneType' is not iterable

**Comment by davidalejandroaguilar** [comment]
Same stack trace:

Please report this error to GitSavvy:

argument of type 'NoneType' is not iterable

```
Traceback (most recent call last):
  File "/home/david/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 215, in git
    stdout, stderr = self.decode_stdout(stdout), self.decode_stdout(stderr)
  File "/home/david/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 265, in decode_stdout
    fallback_encoding = self.savvy_settings.get("fallback_encoding")
  File "/home/david/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/settings.py", line 14, in get
    if key in project_savvy_settings:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kaste** [comment]
Closing as fixed.
