### ISSUE TITLE
Missing syntax highlighting and errors

### ISSUE THREAD

**Issue by p3lim** [timbrel/GitSavvy#1110]
- Sublime Text **3189**
- GitSavvy **2.17.6**
- Git **2.20.1**
- Windows 10 Enterprise 1809

When I want to diff a file, I have two issues, both of which were already closed as an issue years ago:

1. When I start an inline diff, I get a error popup, the view is black and white, exactly the same as in #2.
    To make it work again, I have to close the view, then diff again.
2. When I now have the diff shown without an error, there's no syntax highlighting, exactly the same as in #386. To make it work again, I have to manually set the language.

Issue 1 happens every time I diff a file I haven't diffed yet.  
Issue 2 happens every time I diff a file.

So this means, for every file I want to diff, I have to do the following:
1. Diff the file
2. Close the error window
3. Close the view
4. Diff the file again
5. Set the language manually

This is getting on my nerves, and it seems the Gitter channel is pretty much dead (I brought this up a month ago).

**Comment by p3lim** [comment]
Both issues are also present on the release/2.18.0 branch.

**Comment by p3lim** [comment]
More specifically, the 2nd issue doesn't happen to every language, but it's reproducible with Lua at the very least.

**Comment by randy3k** [comment]
Would you capture the exact error message of issue 1?

**Comment by p3lim** [comment]
```
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.yml.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
error: Error loading colour scheme Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme: Unable to open Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme
Traceback (most recent call last):
  File "C:\Users\p3lim\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 202, in <lambda>
    sublime.set_timeout_async(lambda: self.verify_not_conflict(), 0)
  File "C:\Users\p3lim\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 323, in verify_not_conflict
    fpath = self.get_rel_path()
  File "C:\Users\p3lim\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 482, in get_rel_path
    return os.path.relpath(os.path.realpath(path), start=self.repo_path)
  File "C:\Users\p3lim\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 448, in repo_path
    return self.get_repo_path()
  File "C:\Users\p3lim\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\git_command.py", line 431, in get_repo_path
    raise RuntimeError("Window does not exist.")
RuntimeError: Window does not exist.
```

**Comment by randy3k** [comment]
Does the file `Packages/User/GitSavvy/GitSavvy.active-diff-view.php.hidden-tmTheme` exist?

**Comment by p3lim** [comment]
It gets created the 2nd time I open the diff view.

**Comment by randy3k** [comment]
I could reproduce issue 1. However, I'm too sleep to track it now. Let me check it over the weekend.

**Comment by kaste** [comment]
2.19.0 ships a fix for this.
