### ISSUE TITLE
zipimport.ZipImportError: bad local file header (GitSavvy no longer work since update)

### ISSUE THREAD

**Issue by reagle** [timbrel/GitSavvy#1290]
I saw a package update today, but can no longer use it. I uninstalled and reinstalled, and get this error.

```
GitSavvy: Reloading plugin after install.
reloading plugin GitSavvy.__init__
[Package Reloader] reload failed. ---------------------------------------------
Exception in thread Thread-62237:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/util/reload.py", line 118, in reload_package
    sublime_plugin.reload_plugin(plugin)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /Users/reagle/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package
```

**Comment by kaste** [comment]
Hm. Just from error message I would say you had a download error t.i. the file downloaded kind of successfully but is corrupted.

Maybe just uninstall, restart, make sure Package Control doesn't update anything. Then install again, wait and maybe restart again.

If everything fails manually clone the repo to get you up again, and try some time later because I don't know if you otherwise subscribed to the alpha channel t.i. I don't know if or how Sublime automatically updates a cloned repo.

**Comment by reagle** [comment]
Thanks you, after a few more restarts and reisntalls it seems to work now.

**Comment by kaste** [comment]
💐
