### ISSUE TITLE
Review pull request -> view diff -> KeyError: 'Content-Type'

### ISSUE THREAD

**Issue by maxim** [timbrel/GitSavvy#1312]
When going to `github: review pull request` -> `[pick one]` -> `View diff.` a blank tab opens, and console receives this error:

```
Traceback (most recent call last):
  File "/Users/max/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/github/commands/pull_request.py", line 92, in on_select_action
  File "/Users/max/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/github/commands/pull_request.py", line 132, in view_diff_for_pr
  File "/Users/max/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/interwebs.py", line 71, in request_url
  File "/Users/max/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/interwebs.py", line 40, in request
KeyError: 'Content-Type'
```

This happens consistently on all PRs on all repos I tried (all private). The auth token is correct (pull requests list shows up perfectly). If I change it to an incorrect one, I get a proper message telling me to set it.

ST3 3210
GitSavvy v2.23.0

I was just trying to explore GitSavvy a bit more, never used github integration before. 🙂

**Comment by kaste** [comment]
Haha, I noticed that yesterday.  GitHub changed their server and now the http headers are lower cased on this endpoint.  Other endpoints still are human cased.  

Ideally we just find an open source, no strings attached case-insensitive dict for python.
