### ISSUE TITLE
fatal: unable to fork

### ISSUE THREAD

**Issue by pokidovea** [timbrel/GitSavvy#1332]
The plugin has stopped working unexpectedly. None of commands work: pull, push, fetch. 
```
Traceback (most recent call last):
  File "/home/pokidovea/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/commands/pull.py", line 40, in run_async
  File "/home/pokidovea/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/commands/pull.py", line 16, in do_pull
  File "/home/pokidovea/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/git_mixins/remotes.py", line 54, in pull
  File "/home/pokidovea/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 277, in git
GitSavvy.core.exceptions.GitSavvyError: $ git pull origin develop

fatal: unable to fork
```
All commands work directly from console.

Sublime Text 3, build 3211
OS Ubuntu 18.04.4

**Comment by kaste** [comment]
Hm. Restart?  Something happened to your system but I have of course no idea what.  https://stackoverflow.com/a/20732548 comes to my mind.

**Comment by pokidovea** [comment]
Solved. That was because of another plugin [ProjectEnvironment](https://packagecontrol.io/packages/ProjectEnvironment). I switched off this plugin and all git commands started working. 
Sorry for disturbing.
