### ISSUE TITLE
Creating HTML Sheet causes exception in the plugin

### ISSUE THREAD

**Issue by rchl** [timbrel/GitSavvy#1341]
```py
window.new_html_sheet('Title', 'Content')
```

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1385, in run_
    return self.run(edit)
  File "/Users/me/Library/Application Support/Sublime Text/Installed Packages/GitSavvy.sublime-package/core/commands/status_bar.py", line 53, in run
  File "/Users/me/Library/Application Support/Sublime Text/Installed Packages/GitSavvy.sublime-package/core/settings.py", line 12, in get
AttributeError: 'NoneType' object has no attribute 'settings'
```

HTML Sheets are new in ST4 and those trip a lot of plugins.

**Comment by kaste** [comment]
Duplicate of #1201 

This comes from a (horrible) design/architecture mistake in the code.   Thanks for pointing out that I should tackle this one because it *does* matter.
