### ISSUE TITLE
Errors after upgrade

### ISSUE THREAD

**Issue by asellitt** [timbrel/GitSavvy#1451]
Sometimes gitsavvy just doesnt load at all (possibly similar to this issue: https://github.com/timbrel/GitSavvy/issues/1410). 

This time I saw a bunch of errors while it was installing an upgrade (v2.28.0). Heres what the console shows, I've tried to remove a bunch of noise, hopefully i havent removed too much:

```
startup, version: 3210 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /HOME_DIR/Library/Application Support/Sublime Text 3/Packages
state path: /HOME_DIR/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /HOME_DIR/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Markdown", "Vintage"]
pre session restore time: 0.877443
using gpu buffer for window
startup time: 0.982633
...snip...
reloading plugin GitSavvy.__init__
reloading plugin GitSavvy.git_savvy
plugins loaded
Indexing gherkin phrases done
Package Control: Installing 4 upgrades
ignored packages updated to: ["A File Icon", "GitSavvy", "JsPrettier", "Markdown", "MarkdownEditing", "Vintage"]
...snip...
unloading plugin GitSavvy.__init__
unloading plugin GitSavvy.git_savvy
reloading settings Packages/GitSavvy/GitSavvy.sublime-settings
reloading settings Packages/GitSavvy/syntax/blame.sublime-settings
reloading settings Packages/GitSavvy/syntax/branch.sublime-settings
reloading settings Packages/GitSavvy/syntax/diff.sublime-settings
reloading settings Packages/GitSavvy/syntax/diff_view.sublime-settings
reloading settings Packages/GitSavvy/syntax/graph.sublime-settings
reloading settings Packages/GitSavvy/syntax/make_commit.sublime-settings
reloading settings Packages/GitSavvy/syntax/rebase.sublime-settings
reloading settings Packages/GitSavvy/syntax/show_commit.sublime-settings
reloading settings Packages/GitSavvy/syntax/status.sublime-settings
reloading settings Packages/GitSavvy/syntax/tags.sublime-settings
...snip...
Package Control: Upgraded GitSavvy to 2.28.0
generating syntax summary
ignored packages updated to: ["JsPrettier", "Markdown", "MarkdownEditing", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin GitSavvy.__init__
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /HOME_DIR/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package
reloading plugin GitSavvy.git_savvy
reloading settings Packages/GitSavvy/GitSavvy.sublime-settings
reloading settings Packages/GitSavvy/syntax/blame.sublime-settings
reloading settings Packages/GitSavvy/syntax/branch.sublime-settings
reloading settings Packages/GitSavvy/syntax/diff.sublime-settings
reloading settings Packages/GitSavvy/syntax/diff_view.sublime-settings
reloading settings Packages/GitSavvy/syntax/graph.sublime-settings
reloading settings Packages/GitSavvy/syntax/make_commit.sublime-settings
reloading settings Packages/GitSavvy/syntax/rebase.sublime-settings
reloading settings Packages/GitSavvy/syntax/show_commit.sublime-settings
reloading settings Packages/GitSavvy/syntax/status.sublime-settings
reloading settings Packages/GitSavvy/syntax/tags.sublime-settings
generating syntax summary
generating meta info summary
...snip...
GitSavvy: Reloading plugin after install.
reloading plugin GitSavvy.__init__
[Package Reloader] reload failed. ---------------------------------------------
reloading plugin GitSavvy.__init__
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/HOME_DIR/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/util/reload.py", line 119, in reload_package
    sublime_plugin.reload_plugin(plugin)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /HOME_DIR/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/HOME_DIR/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/util/reload.py", line 129, in reload_package
    sublime_plugin.reload_plugin(plugin)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /HOME_DIR/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package
```

Let me know if there's any other info you need

**Comment by asellitt** [comment]
re opening sublime text after this error loads gitsavvy (same version: 2.28.0) and sometimes it loads without issues

**Comment by kaste** [comment]
Thanks for issue, iirc from the work on SublimeLinter the zip import error is really an "edge" case of the PackageControl package.  Then the downloaded zip/package file is really corrupt and Package Control will fix it on the next, or next next ..., restart.

**Comment by kaste** [comment]
The reference issue is still https://github.com/wbond/package_control/issues/947
But https://github.com/SublimeLinter/SublimeLinter/pull/1249#issuecomment-375749816 has the best comment.  

So the download is not not corrupt, but zipping the package happens actually on the users computer, and there is a race between Sublime getting the file changed notification for the package file (and initiating the load) but the zipping/writing has not yet finished.  (That's how I understand it.)

**Comment by asellitt** [comment]
Ah thanks. So it probably makes sense to close this issue then?

There's still something going on every so often (potentially after an upgrade) where Gitsavvy doesnt load, but this doesnt seem to be the root cause of it. If it comes up again, i'll try to capture the console output and open another issue.

**Comment by kaste** [comment]
Yeah, sounds good.  I just released a hotfix, so the next upgrade will probably on the next start.
