### ISSUE TITLE
GitSavvy upgrade has broken GitSavvy for me (possibly)

### ISSUE THREAD

**Issue by LozmindaSnr** [timbrel/GitSavvy#1486]
Sorry sorry sorry. Forgot to restart ST3 and try again. All good. Massive Face Palm. D'oh !
Apologies again, & Phew !!!

Everthing was fine, I guess an update has occured due to the message that appeared on an ST3 tab. Maybe I did something wrong not sure (I did nothing) then noticed GS wasn't responding. Shut tabs with GS then tried to reopen with GS:Status, nothing. Checked control panel and it contains this error: (Sorry it's quite long)
Package Control: Error parsing JSON from repository https://packagecontrol.io/packages/PackageDev.
Package Control: Error parsing JSON from repository https://packagecontrol.io/packages/PackageDev.
Package Control: Installing 1 upgrades
ignored packages updated to: ["Diff", "GitSavvy", "SublimeLinter-clang", "Vintage"]
unloading plugin GitSavvy.__init__
unloading plugin GitSavvy.git_savvy
reloading settings Packages/GitSavvy/GitSavvy.sublime-settings
reloading settings Packages/GitSavvy/syntax/blame.sublime-settings
reloading settings Packages/GitSavvy/syntax/branch.sublime-settings
reloading settings Packages/GitSavvy/syntax/diff.sublime-settings
reloading settings Packages/GitSavvy/syntax/diff_view.sublime-settings
reloading settings Packages/GitSavvy/syntax/graph.sublime-settings
reloading settings Packages/GitSavvy/syntax/make_commit.sublime-settings
reloading settings Packages/GitSavvy/syntax/rebase.sublime-settings
reloading settings Packages/GitSavvy/syntax/show_commit.sublime-settings
reloading settings Packages/GitSavvy/syntax/status.sublime-settings
reloading settings Packages/GitSavvy/syntax/tags.sublime-settings
generating syntax summary
generating meta info summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Upgraded GitSavvy to 2.30.0
ignored packages updated to: ["Diff", "SublimeLinter-clang", "Vintage"]
reloading plugin GitSavvy.__init__
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /home/elitebook/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package
reloading plugin GitSavvy.git_savvy
reloading settings Packages/GitSavvy/GitSavvy.sublime-settings
reloading settings Packages/GitSavvy/syntax/blame.sublime-settings
reloading settings Packages/GitSavvy/syntax/branch.sublime-settings
reloading settings Packages/GitSavvy/syntax/diff.sublime-settings
reloading settings Packages/GitSavvy/syntax/diff_view.sublime-settings
reloading settings Packages/GitSavvy/syntax/graph.sublime-settings
reloading settings Packages/GitSavvy/syntax/make_commit.sublime-settings
reloading settings Packages/GitSavvy/syntax/rebase.sublime-settings
reloading settings Packages/GitSavvy/syntax/show_commit.sublime-settings
reloading settings Packages/GitSavvy/syntax/status.sublime-settings
reloading settings Packages/GitSavvy/syntax/tags.sublime-settings
generating syntax summary
generating meta info summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
GitSavvy: Reloading plugin after install.
reloading plugin GitSavvy.__init__
[Package Reloader] reload failed. ---------------------------------------------
reloading plugin GitSavvy.__init__
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/home/elitebook/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/common/util/reload.py", line 119, in reload_package
    sublime_plugin.reload_plugin(plugin)
  File "/opt/sublime_text/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /home/elitebook/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/home/elitebook/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/common/util/reload.py", line 129, in reload_package
    sublime_plugin.reload_plugin(plugin)
  File "/opt/sublime_text/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /home/elitebook/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package

Any help much appreciated (I can't get it to talk to gitlab directly) but otherwise for day to day stuff it's great ! Thanks

Ps It's so useful, I've forgotten how to do everything from the command line, darn it !

**Comment by kaste** [comment]
When you see a zipimport.ZipImportError you downloaded a corrupt package.  On next restart Package Control will try to fix this automatically.
