### ISSUE TITLE
`git: diff` stoped working

### ISSUE THREAD

**Issue by oleksiyskononenko** [timbrel/GitSavvy#1577]
First, thanks for the awesome package, I've been using it for years and had no issues so far.
 
However, as of this week when I'm doing `git: diff` GitSavvy shows me a blank tab, no matter if there are actually any changes to the files or not. When I do `git diff` in the command line in a terminal, it works just fine. All the other GitSavvy commands also work. 

Is it a known problem?

Some system info:
- Sublime `4126`
- GitSavvy `2.34.0`
- MacOS `10.15.7`

**Comment by kaste** [comment]
That's not a known issue 😁  We also did not update/release since 1 month or so.  Did you just restarted Sublime Text and it upgraded?  Any messages in the Sublime's console? Yeah, sure some messages.

**Comment by oleksiyskononenko** [comment]
Nope, unfortunately no messages in the console when I do `git: diff`. However, I've tried to reinstall the package and here is what I get

```
ignored packages updated to: ["GitSavvy", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading settings Packages/GitSavvy/GitSavvy.sublime-settings
reloading settings Packages/GitSavvy/syntax/blame.sublime-settings
reloading settings Packages/GitSavvy/syntax/branch.sublime-settings
reloading settings Packages/GitSavvy/syntax/diff.sublime-settings
reloading settings Packages/GitSavvy/syntax/diff_view.sublime-settings
reloading settings Packages/GitSavvy/syntax/graph.sublime-settings
reloading settings Packages/GitSavvy/syntax/make_commit.sublime-settings
reloading settings Packages/GitSavvy/syntax/output_panel.sublime-settings
reloading settings Packages/GitSavvy/syntax/rebase.sublime-settings
reloading settings Packages/GitSavvy/syntax/show_commit.sublime-settings
reloading settings Packages/GitSavvy/syntax/status.sublime-settings
reloading settings Packages/GitSavvy/syntax/tags.sublime-settings
reloading python 3.3 plugin GitSavvy.__init__
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /Users/oleksiy/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package
reloading python 3.3 plugin GitSavvy.git_savvy
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
GitSavvy: Reloading plugin after install.
reloading python 3.3 plugin GitSavvy.__init__
[Package Reloader] reload failed. ---------------------------------------------
reloading python 3.3 plugin GitSavvy.__init__
Exception in thread Thread-79:
Traceback (most recent call last):
  File "/Users/oleksiy/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/util/reload.py", line 119, in reload_package
    sublime_plugin.reload_plugin(plugin)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /Users/oleksiy/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/oleksiy/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/common/util/reload.py", line 129, in reload_package
    sublime_plugin.reload_plugin(plugin)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in /Users/oleksiy/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package
```

Looks like it can't install GitSavvy properly for some reason?

**Comment by oleksiyskononenko** [comment]
I have just restarted my computer and `git: diff` works fine again. Not sure what the problem was, but you can probably close the issue.

**Comment by kaste** [comment]
The `ZipImportError` is really a corrupt download.  🤷
