### ISSUE TITLE
`fatal: not a git repository` on opening files under `~/.config` with YADM enabled

### ISSUE THREAD

**Issue by iamkroot** [timbrel/GitSavvy#1716]
I use [YADM](https://yadm.io) to manage my dotfiles on linux. It creates a git directory under `$HOME/.local/share/yadm/repo.git` but the git root remains `$HOME`.

This seems to confuse git/gitsavvy - I get the following error on opening a file under `~/.config/sublime-text/Packages/User/aoc_scaffold.py`

```
Traceback (most recent call last):
  File "/home/kroot/.config/sublime-text/Installed Packages/GitSavvy.sublime-package/core/runtime.py", line 216, in task
  File "/home/kroot/.config/sublime-text/Installed Packages/GitSavvy.sublime-package/core/commands/status_bar.py", line 25, in run_impl
  File "/home/kroot/.config/sublime-text/Installed Packages/GitSavvy.sublime-package/core/git_mixins/status.py", line 110, in update_working_dir_status
  File "/home/kroot/.config/sublime-text/Installed Packages/GitSavvy.sublime-package/core/git_mixins/status.py", line 114, in get_working_dir_status
  File "/home/kroot/.config/sublime-text/Installed Packages/GitSavvy.sublime-package/core/git_mixins/status.py", line 105, in _get_status
  File "/home/kroot/.config/sublime-text/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 383, in git
GitSavvy.core.exceptions.GitSavvyError: $ git status --porcelain -z -b

fatal: not a git repository: /home/kroot/.config/sublime-text/Packages/User/$HOME/.local/share/yadm/repo.git

```

I do get the same error on simply running `git status` under `/home/kroot/.config/sublime-text/Packages/User/`, so it seems this is more of a git issue. Not sure how it is concatenating the yadm path. I haven't set `GIT_DIR` or `GIT_WORK_TREE` env vars.

**Comment by kaste** [comment]
Just to be clear: if you run `git status` on the command line it bails out showing `/home/kroot/.config/sublime-text/Packages/User/$HOME/.local/share/yadm/repo.git` as "not a git repository"? 

You do have a `.git` under `$HOME`, right?  And that's a file pointing to `$HOME/.local/share/yadm/repo.git`?  

I would've expected you don't have such a link or anything indicating a git repository, t.i. calling `git` would yield `fatal: not a git repository (or any of the parent directories)`, and you would need `yadm` to actually access the config repository.

**Comment by iamkroot** [comment]
> if you run git status on the command line it bails out showing

Correct.

> You do have a .git under $HOME, right? And that's a file pointing to $HOME/.local/share/yadm/repo.git?

Ahh, you helped me look in the right direction. I did not have a `.git` under `$HOME`, but I did somehow end up with a `.git` file inside `$HOME/.config/sublime-text/Packages/User/`. Removing this helped fix the issue. Thanks a lot!
